### PR TITLE
Allow lower cases when matching kinds

### PR DESCRIPTION
**Pull request by max8899**
Signed-off-by: Lei Gong <lgong@alauda.io>

### CODE REVIEW

**Comment by hangyan** [comment]
为啥这样改

**Comment by max8899** [comment]
匹配Kind大小写，有时客户端拿到的是小写，转不回camel case

**Comment by hangyan** [comment]
为啥会拿到小写的kind,奇怪

**Comment by max8899** [comment]
小写的kind是从url拿到的

**Comment by max8899** [comment]
fix in https://github.com/alauda/cyborg/pull/4

**Pull request closed without merging**
